# 04.조건문(Condition)

## 복습해볼까요?(1단계)

### 문제1
다음과 같이 변수 a, b가 있을 때, a가 b보다 크면 'a가 b보다 큽니다'를 출력하는 코드를 작성하세요.

In [ ]:
a = 20
b = 10

if a>b:
  print('{}가 {}보다 큽니다.'.format(a,b))

20가 10보다 큽니다.

### 문제2
이번에는 a가 b보다 크거나 같을 때 'a가 b보다 크거나 같다'를 출력하고, 그렇지 않다면 'b가 a보다 크다'를 출력하는 코드를 작성하세요.

In [ ]:
if a>=b:
  print('{}가 {}보다 크거나 같다'.format(a,b))
else:
  print('{}가 {}보다 크다'.format(b,a))

20가10보다 크거나 같다

### 문제3
다음과 같이 변수 num1, num2이 있을 때,

num1이 num2보다 크면 'num1이 더 큽니다'를 출력하고,

num1과 num2의 값이 같으면 '두 값이 일치합니다'를 출력하고,

num1이 num2보다 작으면 'num2이 더 큽니다'를 출력하는 코드를 작성하세요.

In [ ]:
num1 = 512
num2 = 512

if num1>num2:
  print('{}이 더 큽니다.'.format(num1))
elif num1==num2:
  print('두 값이 일치합니다.')
else:
  print('{}이 더 큽니다.'.format(num2))

두 값이 일치합니다.

### 문제4
다음과 같이 문자열 데이터가 들어있는 변수 str1, str2가 있을 때, 

두 문자열이 일치하면 '텍스트가 일치합니다'를 출력하고, 

일치하지 않을 땐 '텍스트가 일치하지 않습니다'를 출력하는 코드를 작성하세요.

In [ ]:
str1 = '오늘 배울 내용은 04조건문 입니다!'
str2 = '내일 배울 내용은 05반복문 입니다!'

if str1 == str2:
  print('텍스트가 일치합니다.')
else:
  print('텍스트가 일치하지 않습니다.')

텍스트가 일치하지 않습니다.

### 문제5
'and' 연산자와 'or' 연산자를 통해 if문의 조건식을 여러 개 만들 수 있습니다.

다음과 같이 변수 num이 있을 때, 1보다 크고 100보다 작으면 'pass'를 출력하는 코드를 작성해보세요.

In [ ]:
# 힌트 : 조건식 부분에 1 < num and num < 100 입력
num = 55

if 1<num & num<100:
  print('pass')

pass

## 난이도업!(2단계)

### 문제1
다음과 같이 주민번호가 담긴 문자열이 있다.

여성의 주민번호일 때 '여성'을 출력하고, 남성의 주민번호일 땐 '남성'을 출력하는 코드를 작성하세요.

(7번째 짜리 숫자가 1이면 남자, 2는 여자)

In [1]:
id = '210101-1231234'
if id[7] ==2:
  print("여성")
else:
  print("남성")

남성

### 문제2
다음과 같이 전화번호가 담긴 문자열이 있다.

앞 3자리가 '031'로 시작하면 '수원시 전화번호입니다'를 출력하고,

앞 3자리가 '032'로 시작하면 '인천시 전화번호입니다'를 출력하는 코드를 작성하세요.

In [2]:
number = '031-123-1234'
#number = '032-123-1234'

if number[0:3]=='031':
  print("수원시 전화번호입니다.")
elif number[0:3]=='032':
  print("인천시 전화번호입니다.")

수원시 전화번호입니다.

### 문제3
다음과 같이 리스트가 있을 때, 리스트 안에 데이터가 1개 이상이면 '리스트 안에 데이터는 총 __개 입니다'를 출력하고,

데이터가 0개면 '리스트 안에 데이터가 없습니다'를 출력하는 코드를 작성하세요.

In [3]:
list = [10, 30, 20, 40, 32, 50, 55, 50, 32, 84, 40, 88, 99, 100]

if len(list)==0:
  print('리스트 안에 데이터가 없습니다.')
else:
  print('리스트 안에 데이터는 총 {} 개 입니다.'.format(len(list)))

리스트 안에 데이터는 총 14 개 입니다.

### 문제4
다음과 같이 이름, 나이, 성별이 담긴 리스트가 있다.

나이가 20살 이상일 때 '성인입니다'를 출력하는 코드를 작성하세요.

In [4]:
id = ['홍길동', '24', '남자'] #현재 '24'는 문자열 데이터! => 자료형변환 필요

if int(id[1]) >= 20:
  print('성인입니다.')

성인입니다.

### 문제5
나이가 20살 이상일 때, 성별이 '남자'이면 '성인 남성입니다'를 출력하고,

성별이 '여자'이면 '성인 여성입니다'를 출력하는 코드를 작성하세요. 

(if문 이중으로 사용하기!)

In [5]:
id = ['홍길순', '24', '여자']

if int(id[1]) >= 20:
  if id[2]=='남자':
    print('성인 남성입니다.')
  else:
    print('성인 여성입니다')

성인 여성입니다

### 문제6
나이가 20살인지와 성별에 따라 각각 '미성년자 남성', '성인 남성', '미성년자 여성', '성인 여성'을 출력하는 코드를 작성하세요.

In [6]:
id = ['홍길동', '14', '남자']

### 문제7
성적이 담긴 변수 score가 있다. 

만약 score가 90점 이상이면 'A', 80점 이상 90점 미만이면 'B', 

70점 이상 80점 미만이면 'C', 그 이외엔 'F'를 출력하는 코드를 작성하세요.

In [7]:
score = 85

if score>= 90:
  print('A')
elif score>=80 & score<90:
  print('B')
elif score>=70 & score<80:
  print('C')
else:
  print('F')

B

### 문제8
score가 90점 이상이면 'A', 80점 이상 90점 미만이면 'B', 

70점 이상 80점 미만이면 'C', 그 이외엔 'F'를 새로운 변수 result에 입력하세요. 

그러고나서 and 또는 or 연산자를 사용하여 result가 'A', 'B', 'C' 이면 '합격', 'F'이면 '불합격'을 출력하는 코드를 작성하세요.

In [8]:
score = 85

if score>= 90:
  result = 'A'
elif score>=80 & score<90:
  result = 'B'
elif score>=70 & score<80:
  result = 'C'
else:
  result = 'F'

if result == 'A'or'B'or'C':
  print('합격')
else:
  print('불합격')

합격

### 문제9
다음과 같이 과일과 가격 정보가 문자열로 담긴 fruit 딕셔너리가 있다.

fruit에 '사과'가 있는지, 있으면 가격을 출력하고, 

없으면 '없습니다'를 출력하는 코드를 작성하세요.

(코드에 최대한 '사과', '5000'을 직접적으로 사용하지 않도록 해보세요!)

In [9]:
fruit = {'사과' : '5000', '바나나' : '7000', '망고' : '8000'}
apple = '사과'

if bool(fruit.get(apple)) == False:
  print('없습니다')
elif bool(fruit.get(apple)) == True:
  print(fruit.get(apple))

5000

### 문제10
바나나를 사려고 하는데, 가진 돈이 5000원 밖에 없다.

바나나의 가격이 5000원을 넘으면 '구매가 불가능합니다'라고 출력하고,

5000원 이하면 '구매가능합니다'가 출력되도록 코드를 작성하세요.

In [10]:
fruit = {'사과' : '5000', '바나나' : '7000', '망고' : '8000'} #가격 자료형 유의!

if int(fruit.get('바나나')) > 5000:
  print('구매가 불가능합니다.')
else: print('구매가 가능합니다')

구매가 불가능합니다.

### 문제 11
다음과 같이 4개의 성적이 담긴 리스트 score가 있다.

4개 성적의 평균이 60점 이상이고, 각 점수에 40점 미만의 점수가 없어야 '합격'일 때,

합격인지 불합격인지 출력하는 코드를 작성하세요.

In [11]:
score = [55, 90, 80, 35]
#score = [40, 40, 40, 40]
n = len(score)

sum=0
for i in range(0,n):
  if score[i] <40:
    print('불합격')
    break
  else:
    sum=sum+score[i]
    if i == n-1:
      avr= sum / n
      if avr>60:
        print('합격')
      else:
        print('불합격')

불합격

### 문제12
다트를 던져서 50점과 가까울수록 높은 점수를 매긴다 할 때,

45점 이상 55점 미만일 때 '+10점',

40점 이상 60 미만일 때 '+7점',

30점 이상 70점 미만일 때 '+5점'을 출력하는 코드를 작성하세요.

In [12]:
score = 43

if score>=30 and score<70:
  score+=5
  print('+5점')
elif score>=40 and score<60:
  if score>=45 and score<55:
    score+=10
    print('+10점')
  else:
    score+=7
    print('+7점')

print(score)

+5점
48

### 문제13
현재 몇 월인지 데이터를 입력한 변수 month가 있다. 

month가 3 ~ 5월일 땐 '봄', 6 ~ 8월일 땐 '여름', 

9 ~ 11월일 땐 '가을', 12 ~ 2월일 땐 '겨울'이 출력되도록 코드를 작성하세요.

In [13]:
month = 

if month>=3 and month <=5:
  print('봄')
elif month>=6 and month <=8:
  print('여름')
elif month>=9 and month <=11:
  print('가을')
elif month<=12 and month >0:
  print('겨울')

SyntaxError: ignored

## 도전해보기!(3단계)

### 문제1
다음과 같이 세 사람의 성적 3개가 담긴 딕셔너리 score가 있다.

if문을 사용하여 총합이 가장 높은 사람을 출력하는 코드를 작성하세요.

(list가 있을 때 함수 sum(list)를 통해 list의 총 합을 구할 수 있습니다!)

In [ ]:
# sum함수 사용 안됨 <6/28 4pm>
list=[1,2,3,4]

def sum(list):
  n=len(list)
  sum=0
  for i in range(0,n):
    sum+=list[i]
  return(sum)  

sum(list)

10

In [ ]:
score = {'지수' : [90, 80, 70], '민지' : [95, 100, 90], '현정' : [80, 90, 95]}



if sum(score['지수'])>sum(score['민지']):
  if sum(score['지수'])>sum(score['현정']):
    print('지수')
  else: print('현정') 
else:
  if sum(score['민지'])>sum(score['현정']):
    print('민지')   
  else: print('현정')

민지

### 문제2
사과 2개, 망고 3개, 수박 1개를 사려고 한다.

살 수 없는 과일을 출력하고, 살 수 있는 과일은 구입할 갯수와 가격을 계산해 총 가격을 출력해보세요.(코드 형식 무관)

In [ ]:
fruit = {'apple' : '5000', 'banana' : '7000', 'mango' : '8000'}

keys=fruit.keys()

apple = 2
mango = 3
watermelon = 1

wanted={'apple':2,'mango':3,'watermelon':1}
keys_w=wanted.keys()

price = 0 #총가격을 담고 있는 변수

for k in keys:
  for w in keys_w:
    if k == w:
      price += (int(fruit[k]) * int(wanted[w]))
price

34000

### 문제3-1
다음과 같이 음식 정보가 담긴 딕셔너리 menu가 있다.

'일반떡볶이'의 경우 '맵기'가 4단계 또는 5단계는 추가요금 500원이 붙는다고 할 때,

if문을 사용하여 '일반떡볶이'의 맵기별 가격 데이터가 담긴 리스트를 만들어 해당 리스트를 출력해보세요.

( 출력결과 : [5000, 5000, 5000, 5500, 5500] )

In [ ]:
menu = {'로제떡볶이' : {'맵기' : [1, 2, 3], '가격' : 7000},
        '투움바떡볶이' : {'맵기' : [1, 2, 3], '가격' : 7000},
        '일반떡볶이' : {'맵기' : [1, 2, 3, 4, 5], '가격' : 5000}}

price = []  #맵기별 가격 데이터가 담긴 리스트

s_p=menu['일반떡볶이']

s=s_p['맵기']
p=s_p['가격']

n = len(s)

for i in range(0,n):
  if i>=3 :
    price.append(p+500)
  else:
    price.append(p)


price

[5000, 5000, 5000, 5500, 5500]

#### 문제3-1 힌트 (먼저 코드를 입력해보고, 안 될 때 보기!)

In [ ]:
# menu['일반떡볶이']['맵기'][0] 를 출력하면 [1,2,3,4,5]의 '1'이 출력된다. 이 값을 이용하여 조건식을 만들자

if menu['일반떡볶이']['맵기'][0] <= 3 :
    price.append(menu['일반떡볶이']['가격'])   #price.append()를 통해 price리스트에 값을 추가할 수 있다.
else :
    price.append(menu['일반떡볶이']['가격']+500)  #이 조건문 세트를 맵기단계에 따라 5번 반복해주기!

### 문제3-2
로제떡볶이 1단계 맵기 3인분, 짜장떡볶이 2단계 맵기 2인분, 일반떡볶이 5단계 맵기 1인분을 주문하려고 한다. 

주문할 내역정보가 담긴 order 딕셔너리를 이용하여 내야 할 돈을 계산하려고 할 때, 

총 가격은 'price'라는 변수에 누적시켜 계산해야 할 총 가격을 출력하세요. 

(최대한 딕셔너리를 이용하기)

In [ ]:
menu = {'로제떡볶이' : {'맵기' : [1, 2, 3], '가격' : 7000},
        '투움바떡볶이' : {'맵기' : [1, 2, 3], '가격' : 7000},
        '일반떡볶이' : {'맵기' : [1, 2, 3, 4, 5], '가격' : 5000}}

order = {'로제떡볶이' : {'맵기' : 1, '갯수' : 3},
        '짜장떡볶이' : {'맵기' : 2, '갯수' : 2},
        '일반떡볶이' : {'맵기' : 5, '갯수' : 1}}

price = 0

m_k=menu.keys()
o_k=order.keys()

p = 0
for m in m_k:
  print(m)
  for o in o_k:
    if(m == o): 
      print('일치')
      o_kk=order[o].keys()
      for ok in o_kk:
        if(ok=='맵기'):
          print('맵기',order[o][ok])
          if(order[o][ok]>=3):
            print('4,5단계')
            p=menu[m]['가격']+500
            print('4,5가격',p)
          else:
            p=menu[m]['가격']  
            print('1,2,3가격',p)
        else:
          print('갯수',order[o][ok])
          p= p * order[o][ok]
          print(p)
      print('총가격',p)   
      price+=p 

print('최종가격',price)

로제떡볶이
일치
맵기 1
1,2,3가격 7000
갯수 3
21000
총가격 21000
투움바떡볶이
일반떡볶이
일치
맵기 5
4,5단계
4,5가격 5500
갯수 1
5500
총가격 5500
최종가격 26500